"""phase 1: web knowledge data model

Revision ID: 2bb813c0723d
Revises: 059734f1a1c5
Create Date: 2026-08-02 15:31:39.360723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb813c0723d'
down_revision: Union[str, Sequence[str], None] = '059734f1a1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('normalized_storage_key', sa.String(length=512), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('quality_signals_json', sa.Text(), nullable=False),
    sa.Column('is_searchable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_content_hash'), 'document_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_id'), 'document_versions', ['id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'job_type', 'seq', name='uq_job_events_job_type_seq')
    )
    op.create_index(op.f('ix_job_events_id'), 'job_events', ['id'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('knowledge_ingest_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('web_search_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('document_ids_json', sa.Text(), nullable=False),
    sa.Column('counters_json', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['web_search_run_id'], ['web_search_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_ingest_jobs_id'), 'knowledge_ingest_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_ingest_jobs_message_id'), 'knowledge_ingest_jobs', ['message_id'], unique=False)
    op.create_index(op.f('ix_knowledge_ingest_jobs_status'), 'knowledge_ingest_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_ingest_jobs_user_id'), 'knowledge_ingest_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_ingest_jobs_web_search_run_id'), 'knowledge_ingest_jobs', ['web_search_run_id'], unique=False)
    op.create_table('web_search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_search_runs_id'), 'web_search_runs', ['id'], unique=False)
    op.create_index(op.f('ix_web_search_runs_message_id'), 'web_search_runs', ['message_id'], unique=False)
    op.create_index(op.f('ix_web_search_runs_session_id'), 'web_search_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_web_search_runs_user_id'), 'web_search_runs', ['user_id'], unique=False)
    op.create_table('knowledge_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_cards_document_version_id'), 'knowledge_cards', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_cards_id'), 'knowledge_cards', ['id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('seed_type', sa.String(length=32), nullable=False),
    sa.Column('seed_url', sa.String(length=2048), nullable=False),
    sa.Column('allowed_domains_json', sa.Text(), nullable=False),
    sa.Column('policy_json', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_id'), 'knowledge_sources', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_user_id'), 'knowledge_sources', ['user_id'], unique=False)
    op.create_table('chat_turn_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('web_search_run_id', sa.Integer(), nullable=True),
    sa.Column('document_version_id', sa.Integer(), nullable=True),
    sa.Column('citation_id', sa.String(length=64), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['web_search_run_id'], ['web_search_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_turn_sources_document_version_id'), 'chat_turn_sources', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_chat_turn_sources_id'), 'chat_turn_sources', ['id'], unique=False)
    op.create_index(op.f('ix_chat_turn_sources_message_id'), 'chat_turn_sources', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_turn_sources_session_id'), 'chat_turn_sources', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_turn_sources_user_id'), 'chat_turn_sources', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_turn_sources_web_search_run_id'), 'chat_turn_sources', ['web_search_run_id'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('counters_json', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_id'), 'crawl_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_idempotency_key'), 'crawl_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_message_id'), 'crawl_jobs', ['message_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_source_id'), 'crawl_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_user_id'), 'crawl_jobs', ['user_id'], unique=False)
    op.create_table('knowledge_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_card_id', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['knowledge_card_id'], ['knowledge_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_evidence_document_version_id'), 'knowledge_evidence', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_evidence_id'), 'knowledge_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_evidence_knowledge_card_id'), 'knowledge_evidence', ['knowledge_card_id'], unique=False)
    op.create_table('crawl_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_pages_canonical_url'), 'crawl_pages', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_crawl_pages_content_hash'), 'crawl_pages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_crawl_pages_id'), 'crawl_pages', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_pages_job_id'), 'crawl_pages', ['job_id'], unique=False)
    op.create_index(op.f('ix_crawl_pages_status'), 'crawl_pages', ['status'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_page_id', sa.Integer(), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_page_id'], ['crawl_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_crawl_page_id'), 'source_snapshots', ['crawl_page_id'], unique=False)
    op.create_index(op.f('ix_source_snapshots_id'), 'source_snapshots', ['id'], unique=False)
    op.add_column('document_chunks', sa.Column('document_version_id', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('document_chunks', sa.Column('content_hash', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('document_chunks', sa.Column('locator_json', sa.Text(), nullable=False, server_default='{}'))
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_version_id'), 'document_chunks', ['document_version_id'], unique=False)
    # NOTE: FK constraints on existing tables skipped for SQLite (no ALTER TABLE ADD CONSTRAINT).
    # FKs are enforced at ORM level; will be created when migrating to PostgreSQL.
    op.add_column('documents', sa.Column('source_type', sa.String(length=32), nullable=False, server_default='upload'))
    op.add_column('documents', sa.Column('canonical_url', sa.String(length=2048), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('source_snapshot_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('quality_status', sa.String(length=32), nullable=False, server_default='pending'))
    op.add_column('documents', sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_documents_canonical_url'), 'documents', ['canonical_url'], unique=False)
    # NOTE: FK constraints on existing tables skipped for SQLite.
    op.add_column('messages', sa.Column('web_mode', sa.String(length=16), nullable=False, server_default='off'))
    op.add_column('messages', sa.Column('knowledge_mode', sa.String(length=16), nullable=False, server_default='off'))
    op.add_column('messages', sa.Column('web_search_run_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('knowledge_ingest_job_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_knowledge_ingest_job_id'), 'messages', ['knowledge_ingest_job_id'], unique=False)
    op.create_index(op.f('ix_messages_web_search_run_id'), 'messages', ['web_search_run_id'], unique=False)
    # NOTE: FK constraints on existing tables skipped for SQLite.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: FK constraints were not created on existing tables for SQLite.
    op.drop_index(op.f('ix_messages_web_search_run_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_knowledge_ingest_job_id'), table_name='messages')
    op.drop_column('messages', 'knowledge_ingest_job_id')
    op.drop_column('messages', 'web_search_run_id')
    op.drop_column('messages', 'knowledge_mode')
    op.drop_column('messages', 'web_mode')
    # NOTE: FK constraints were not created on existing tables for SQLite.
    op.drop_index(op.f('ix_documents_canonical_url'), table_name='documents')
    op.drop_column('documents', 'last_fetched_at')
    op.drop_column('documents', 'quality_status')
    op.drop_column('documents', 'current_version_id')
    op.drop_column('documents', 'source_snapshot_id')
    op.drop_column('documents', 'canonical_url')
    op.drop_column('documents', 'source_type')
    # NOTE: FK constraints were not created on existing tables for SQLite.
    op.drop_index(op.f('ix_document_chunks_document_version_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.drop_column('document_chunks', 'locator_json')
    op.drop_column('document_chunks', 'content_hash')
    op.drop_column('document_chunks', 'chunk_index')
    op.drop_column('document_chunks', 'document_version_id')
    op.drop_index(op.f('ix_source_snapshots_id'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_crawl_page_id'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_crawl_pages_status'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_job_id'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_id'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_content_hash'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_canonical_url'), table_name='crawl_pages')
    op.drop_table('crawl_pages')
    op.drop_index(op.f('ix_knowledge_evidence_knowledge_card_id'), table_name='knowledge_evidence')
    op.drop_index(op.f('ix_knowledge_evidence_id'), table_name='knowledge_evidence')
    op.drop_index(op.f('ix_knowledge_evidence_document_version_id'), table_name='knowledge_evidence')
    op.drop_table('knowledge_evidence')
    op.drop_index(op.f('ix_crawl_jobs_user_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_source_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_message_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_idempotency_key'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_chat_turn_sources_web_search_run_id'), table_name='chat_turn_sources')
    op.drop_index(op.f('ix_chat_turn_sources_user_id'), table_name='chat_turn_sources')
    op.drop_index(op.f('ix_chat_turn_sources_session_id'), table_name='chat_turn_sources')
    op.drop_index(op.f('ix_chat_turn_sources_message_id'), table_name='chat_turn_sources')
    op.drop_index(op.f('ix_chat_turn_sources_id'), table_name='chat_turn_sources')
    op.drop_index(op.f('ix_chat_turn_sources_document_version_id'), table_name='chat_turn_sources')
    op.drop_table('chat_turn_sources')
    op.drop_index(op.f('ix_knowledge_sources_user_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_knowledge_cards_id'), table_name='knowledge_cards')
    op.drop_index(op.f('ix_knowledge_cards_document_version_id'), table_name='knowledge_cards')
    op.drop_table('knowledge_cards')
    op.drop_index(op.f('ix_web_search_runs_user_id'), table_name='web_search_runs')
    op.drop_index(op.f('ix_web_search_runs_session_id'), table_name='web_search_runs')
    op.drop_index(op.f('ix_web_search_runs_message_id'), table_name='web_search_runs')
    op.drop_index(op.f('ix_web_search_runs_id'), table_name='web_search_runs')
    op.drop_table('web_search_runs')
    op.drop_index(op.f('ix_knowledge_ingest_jobs_web_search_run_id'), table_name='knowledge_ingest_jobs')
    op.drop_index(op.f('ix_knowledge_ingest_jobs_user_id'), table_name='knowledge_ingest_jobs')
    op.drop_index(op.f('ix_knowledge_ingest_jobs_status'), table_name='knowledge_ingest_jobs')
    op.drop_index(op.f('ix_knowledge_ingest_jobs_message_id'), table_name='knowledge_ingest_jobs')
    op.drop_index(op.f('ix_knowledge_ingest_jobs_id'), table_name='knowledge_ingest_jobs')
    op.drop_table('knowledge_ingest_jobs')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_document_versions_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_content_hash'), table_name='document_versions')
    op.drop_table('document_versions')
    # ### end Alembic commands ###
